# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          구운 자몽의 단상
baseurl:        ""
url:            "https://bakedgrapefruit.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         구운 자몽
  url:          https://bakedgrapefruit.github.io
  email:        aodrnss@naver.com 
  github:       bakedgrapefruit
  # twitter:      playpingpong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/bakedgrapefruit/bakedgrapefruit.github.io
